apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
  - apiGroups: ["otus.homework"]
    resources: ["mysqls"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["otus.homework"]
    resources: ["mysqls/status", "mysqls/finalizers"]
    verbs: ["update", "patch"]

  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator-role
subjects:
  - kind: ServiceAccount
    name: mysql-operator
    namespace: default
