apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metrics
  labels:
    app: nginx-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metrics
  template:
    metadata:
      labels:
        app: nginx-metrics
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

        - name: exporter
          image: nginx/nginx-prometheus-exporter:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          args:
            - -nginx.scrape-uri=http://localhost/metrics
          ports:
            - containerPort: 9113

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-metrics-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;

        location /metrics {
          stub_status;
          allow all;
        }

        location / {
          return 200 'Nginx is running\n';
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-service
spec:
  selector:
    app: nginx-metrics
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  type: ClusterIP
