apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics-servicemonitor
  namespace: default
  labels:
    release: prometheus-operator-release
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
