apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-service
  labels:
    app: nginx-metrics
spec:
  selector:
    app: nginx-metrics
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
