releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 25.3.5
    installed: true
    values:
      - global:
          namespaceOverride: prod
      - kraft:
          enabled: true
          clusterId: "j1foO9_3SfWrT4G_2QYQ0w"
      - broker:
          replicaCount: 5
      - controller:
          replicaCount: 3
          quorumVoters: "0@kafka-dev-controller-0.kafka-dev-controller-headless.dev.svc.cluster.local:9093,1@kafka-dev-controller-1.kafka-dev-controller-headless.dev.svc.cluster.local:9093,2@kafka-dev-controller-2.kafka-dev-controller-headless.dev.svc.cluster.local:9093"
      - image:
          tag: 3.5.2-debian-12-r30
      - auth:
          clientProtocol: sasl
          interBrokerProtocol: sasl
          sasl:
            mechanism: plain
            jaas:
              clientUsers:
                - user1
              clientPasswords:
                - password1
              interBrokerUser: broker
              interBrokerPassword: brokerpass

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: 25.3.5
    installed: true
    values:
      - global:
          namespaceOverride: dev
      - kraft:
          enabled: true
          clusterId: "yXQhQV4pQhuGP5WJjwARjA"
      - broker:
          replicaCount: 1
      - controller:
          replicaCount: 3
          quorumVoters: "0@kafka-dev-controller-0.kafka-dev-controller-headless.dev.svc.cluster.local:9093,1@kafka-dev-controller-1.kafka-dev-controller-headless.dev.svc.cluster.local:9093,2@kafka-dev-controller-2.kafka-dev-controller-headless.dev.svc.cluster.local:9093"
      - image:
          tag: 3.5.2-debian-12-r30
        auth:
          enabled: false
          clientProtocol: plaintext
          interBrokerProtocol: plaintext
