apiVersion: v1
kind: Service
metadata:
  name: consul-lb
  namespace: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
  selector:
    app: consul
    component: server
