apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes" # <--- исправь вот это
          role: "otus"
          serviceAccountRef:
            name: vault-auth
