apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.nginx.name }}
  namespace: {{ .Values.app.namespace }}
data:
  default.conf: |
{{ .Values.configMaps.nginx.defaultConf | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.appLabel }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.appLabel }}
    spec:
      serviceAccountName: {{ .Values.app.svcAccount }}
      nodeSelector:
        homework: "true"
      volumes:
        - name: {{ .Values.app.volumes.volumeName }}
          persistentVolumeClaim:
            claimName: homework-pvc
        - name: nginx-config
          configMap:
            name: nginx-homework-config
        - name: homework-config-volume
          configMap:
            name: homework-config
      initContainers:
        - name: {{ .Values.app.initContainer.name }}
          image: {{ .Values.app.initContainer.image }}
          command:
            - sh
            - -c
            - |
              {{- .Values.app.initContainer.command | nindent 14 }}
          volumeMounts:
            - name: {{ .Values.app.volumes.volumeName }}
              mountPath: /init
            - name: homework-config-volume
              mountPath: /config
      containers:
        - name: {{ .Values.app.containers.nginx.name }}
          image: {{ .Values.app.containers.nginx.repository }}:{{ .Values.app.containers.nginx.tag }}
          resources:
            {{- toYaml .Values.app.resources.nginx | nindent 12 }}
          {{- if .Values.app.enableProbes }}
          readinessProbe:
            httpGet:
              path: /index.html
              port: {{ .Values.app.containers.probePort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          volumeMounts:
            - name: {{ .Values.app.volumes.volumeName }}
              mountPath: /homework
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: homework-config-volume
              mountPath: /homework/conf
              readOnly: True
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /homework/index.html
          ports:
            - containerPort: {{ .Values.app.containers.containerPort }}

        - name: {{ .Values.app.containers.metrics.name }}
          image: {{ .Values.app.containers.metrics.repository }}:{{ .Values.app.containers.metrics.tag }}
          env:
            {{- toYaml .Values.app.containers.metrics.env | nindent 12 }}
          command:
            - sh
            - -c
            - |
              {{- .Values.app.containers.metrics.command | nindent 14 }}
          volumeMounts:
            - name: {{ .Values.app.volumes.volumeName }}
              mountPath: /homework
          resources: {{- toYaml .Values.app.resources.metrics | nindent 12 }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
