apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-kubelet-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.svcAccount }}
    namespace: {{ .Values.app.namespace }}
roleRef:
  kind: ClusterRole
  name: kubelet-metrics-reader
  apiGroup: rbac.authorization.k8s.io
