apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.namespace }}-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: minikube-hostpath-retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
