apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
