apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.app.appLabel }}
