apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  storageClassName: minikube-hostpath-retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
